files:
  - source: /content/zh-cn/*.md
    translation: /content/%language%/%original_file_name%

  - source: /content/zh-cn/docs/*.md
    translation: /content/%language%/docs/%original_file_name%

  - source: /content/zh-cn/docs/medicine/*.md
    translation: /content/%language%/docs/medicine/%original_file_name%
